import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { FileUpload } from "primereact/fileupload";

import { Tag } from "primereact/tag";

import { Button } from "primereact/button";

import styles from "../styles/Home.module.css";
import { useState } from "react";
import "primereact/resources/themes/bootstrap4-light-blue/theme.css";
// import "primereact/resources/themes/lara-light-teal/theme.css";
// import "primereact/resources/themes/tailwind-light/theme.css"
// import "primereact/resources/themes/saga-green/theme.css"
// import "primereact/resources/themes/rhea/theme.css"
// import "primereact/resources/themes/mdc-light-indigo/theme.css"
// import "primereact/resources/themes/vela-green/theme.css";
import "primereact/resources/primereact.min.css";
import "primeicons/primeicons.css";
import BoxHeader from "../components/Header";

export default function Home() {
  const [files, setFiles] = useState([]);
  const router = useRouter();
  function openFileUploadField() {
    document.getElementById("file").click();
  }

  function fileAdded() {
    console.log("file added");
  }

  const onUpload = () => {
    router.push("/thankyou-page");
  };
  const customItemTemplate = (file, props) => {
    console.log(JSON.stringify(file));
    return (
      <div className="flex align-items-center flex-wrap">
        <div className="flex align-items-center" style={{ width: "40%" }}>
          <img
            alt={file.name}
            role="presentation"
            src={file.objectURL}
            width={100}
          />
          {/* <span className="flex flex-column text-left ml-3">
                        {file.name}
                        <small>{new Date().toLocaleDateString()}</small>
                    </span> */}
        </div>
        <Tag
          value={props.formatSize}
          severity="warning"
          className="px-3 py-2"
        />
        <Button
          type="button"
          icon="pi pi-times"
          className="p-button-outlined p-button-rounded p-button-danger ml-auto"
          onClick={props.onRemove}
        />
        <hr></hr>
      </div>
    );
    // file: Current file object.
    // options.onRemove: Event used to remove current file in the container.
    // options.previewElement: The default preview element in the container.
    // options.fileNameElement: The default fileName element in the container.
    // options.sizeElement: The default size element in the container.
    // options.removeElement: The default remove element in the container.
    // options.formatSize: The formated size of file.
    // options.files: Current files.
    // options.index: The index of file in current files list.
    // options.element: Default element created by the component.
    // options.props: component props.
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>TAMMS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="tamms__container">
        <div className="tamms__content-box">
          <BoxHeader></BoxHeader>
          <div className="tamms__content-box--body">
            <h1>Upload Evidence of Vehicle Damage</h1>
            <p>
              Please upload as many images as possible to show the extent of the
              damage to your vehicle. Remember to include images of all damaged
              areas.
            </p>
            <FileUpload
              name="demo"
              //   url="/api/upload"
              customUpload
              uploadHandler={onUpload}
              multiple
              accept="image/*,video/*"
              chooseLabel="Add"
              cancelLabel="Reset"
              uploadLabel="Submit"
              mode="advanced"
              itemTemplate={customItemTemplate}
            ></FileUpload>
          </div>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
